version: '3.8'

services:
  server:
    build:
      context: ./docker/php
    volumes:
      - ./server:/var/www/html
    ports:
      - "9000:9000"
    working_dir: /var/www/html
    networks:
      - app-network
    command: >
      sh -c "
        if [ ! -f artisan ]; then
          composer create-project laravel/laravel . &&
          php artisan key:generate
        fi &&
        php-fpm"
    depends_on:
      - mysql

  nginx:
    image: nginx:alpine
    volumes:
      - ./server:/var/www/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "8080:80"
    networks:
      - app-network
    depends_on:
      - server

  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: laravel
      MYSQL_USER: laravel
      MYSQL_PASSWORD: secret
    volumes:
      - mysql-data:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - app-network

  client:
    image: node:22-alpine
    working_dir: /app
    volumes:
      - ./client:/app
    command: >
      sh -c "
        if [ ! -f package.json ]; then
          npm create vite@latest . -- --template react-ts;
        fi &&
        npm install &&
        npm run dev -- --host"
    ports:
      - "5173:5173"
    networks:
      - app-network

volumes:
  mysql-data:

networks:
  app-network:
    driver: bridge
